name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.25
  - scipy=1.11
  - matplotlib=3.8
  - h5py=3.9
  - ipykernel>=6
  - decorator=5.1
  - jupyterlab
  - pip
  - pip: